// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

interface ISkaleRNG {
    /**
     * @notice Get a random number from SKALE consensus
     * @return bytes32 Random number generated by the consensus
     */
    function getRandomNumber() external view returns (bytes32);
    
    /**
     * @notice Get the next random number (different from getRandomNumber)
     * @return bytes32 Next random number in the sequence
     */
    function getNextRandomNumber() external view returns (bytes32);
    
    /**
     * @notice Get random number with a specific index
     * @param index The index to get random number for
     * @return bytes32 Random number at the specified index
     */
    function getRandomNumberByIndex(uint256 index) external view returns (bytes32);
}